name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build and dockerize with Jib
        run: mvn clean compile com.google.cloud.tools:jib-maven-plugin:3.1.1:build -Dimage=public.ecr.aws/u1u3e1y1/github-actions:v1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u1u3e1y1
          docker login --username AWS --password-stdin public.ecr.aws/u1u3e1y1/github-actions

      - name: Push image to AWS ECR
        run: docker push public.ecr.aws/u1u3e1y1/github-actions:v1
