name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Build and dockerize with Jib
        run: mvn compile com.google.cloud.tools:jib-maven-plugin:3.4.0:build -Dimage=ghcr.io/mahendra9408/GitHubactions-demo:v1

      - name: Push Docker image to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/mahendra9408/GitHubactions-demo:v1
